#!/usr/bin/env bash

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }
see() ( { set -x; } 2>/dev/null ; "$@" ) ;

qpdf="qpdf.ai"  # AppImage version "installed" to get latest release from https://github.com/qpdf/qpdf/releases/
qpdf="qpdf"     # apt-installed version

command -v "$qpdf" > /dev/null || die "$qpdf needs to be installed"
command -v "pdfgrep" > /dev/null || die "pdfgrep needs to be installed"

firstgrepstr="Detail for Claims Processed on this Explanation of Benefits \(EOB\)"
lastgrepstr="Understanding your Annual Deductible and Out-of-Pocket Limits"

pdfgrep_pgnum() ( pdfgrep -nm1 "$1" "$2" | cut -d: -f1 )

do1file() (
   fullname="$1"
   test -f "$fullname" || die "not a file: $fullname"
   dirname="$(dirname -- "${fullname}")"    # ; echo "dirname   $dirname"
   filename="$(basename -- "${fullname}")"  # ; echo "filename  $filename"
   extension="${filename##*.}"              # ; echo "extension $extension"
   basename="${filename%.*}"                # ; echo "basename  $basename"
   # logical parameters:
   bakdnm="$dirname/originals" ; test -d "$bakdnm" || mkdir -p "$bakdnm"
   outdnm="$dirname/reduced"   ; test -d "$outdnm" || mkdir -p "$outdnm"

   echo "fullname=$fullname"
   firstpg="$(pdfgrep_pgnum "$firstgrepstr" "$fullname")" # ; echo "firstpg=$firstpg"
   (( firstpg > 0 )) || die "invalid firstpg ($firstpg) in $fullname"
   lastpg="$(pdfgrep_pgnum "$lastgrepstr" "$fullname")"   # ; echo "lastpg=$lastpg"
   (( lastpg > 0 )) || die "invalid lastpg ($lastpg) in $fullname"
   (( firstpg < lastpg )) || die "not enough pages ($firstpg < $lastpg) in $fullname"
   see "$qpdf" "$fullname" --pages . "$firstpg"-"$lastpg" -- --rotate=+90 "$outdnm/$filename" || die "$qpdf failed"
   see mv -n "$fullname" "$bakdnm/$filename" || die "backup move failed"
   )

[[ "$1" ]] || echo "missing name of file(s) to rotate"
for fnm in "$@"; do
   do1file "$fnm"
done
