#!/usr/bin/env bash

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }
see() ( { set -x; } 2>/dev/null ; "$@" ) ;

qpdf="qpdf.ai"  # AppImage version "installed" to get latest release from https://github.com/qpdf/qpdf/releases/
qpdf="qpdf"     # apt-installed version
qpdf="qpdf-11.9.1-x86_64.AppImage"  # AppImage version "installed" to get latest release from https://github.com/qpdf/qpdf/releases/
                # qpdf-11.9.1 PRESERVES INTERNAL LINKS IN INCOMING PDFS (big win)!!!

command -v "$qpdf" > /dev/null || die "$qpdf needs to be installed"

see "$qpdf" --empty --pages "$@" -- "output.pdf" || die "$qpdf [$outfnm] failed"
