#!/usr/bin/env bash

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

find_ec_binary() (
   ecxbnm="ebook-convert"
   if command -v "$ecxbnm"; then
      echo "$ecxbnm"
      return 0
   fi

   declare -a calibre_locns=( "$HOME/my/bin"  "$LOCALAPPDATA/Programs" )
   for dnm in "${calibre_locns[@]}"; do
      ecexe="$dnm/Calibre Portable/Calibre/$ecxbnm.exe"
      if [[ -x "$ecexe" ]]; then
         echo "$ecexe"
         return 0
      fi
   done
   die "$ecxbnm is not in PATH or ${calibre_locns[*]}"
   )
ecbin="$(find_ec_binary)"

convert_to_pdf() (
   # https://manual.calibre-ebook.com/generated/en/ebook-convert.html#pdf-output-options
   margin_pts=3
   set -x  # show actual cmdline
   "$ecbin" "$1" "$2" --output-profile=ipad --use-profile-size \
 --pdf-page-margin-bottom=$margin_pts \
 --pdf-page-margin-left=$margin_pts \
 --pdf-page-margin-right=$margin_pts \
 --pdf-page-margin-top=$margin_pts
   )

for fnm in "$@"; do
   echo "arg=$fnm'"
   [[ -f "$fnm" ]] || die "$fnm does not name a file"
   ext="${fnm##*.}"
   if [[ "$ext" && "${ext^^}" == "PDF" ]]; then  # don't try to convert a PDF to PDF
      echo "skipping $ext $fnm"
   else
      if [[ $fnm != */* ]]; then
         fpath=""
      else
         fpath="${fnm%/*}/"
      fi                            ; echo "fpath=$fpath'"
      sanspath="${fnm##*/}"         ; echo "sanspath=$sanspath'"    # https://stackoverflow.com/a/965069
      sansext="${sanspath%.*}"      ; echo "sansext=$sansext'"
      srcfnm="$fnm"                       ; echo "srcfnm=$srcfnm'"
      tgtfnm="$fpath$sansext.medtype.pdf" ; echo "tgtfnm=$tgtfnm'"
      if [[ -f "$tgtfnm" ]]; then
         echo "file $sansext already exists"
      else
         convert_to_pdf "$srcfnm" "$tgtfnm"
      fi
   fi
done
