#!/usr/bin/env bash

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

find_ec_binary() (
   ecxbnm="ebook-convert"
   if command -v "$ecxbnm"; then
      echo "$ecxbnm"
      return 0
   fi

   declare -a calibre_locns=( "$HOME/my/bin"  "$LOCALAPPDATA/Programs" )
   for dnm in "${calibre_locns[@]}"; do
      ecexe="$dnm/Calibre Portable/Calibre/$ecxbnm.exe"
      if [[ -x "$ecexe" ]]; then
         echo "$ecexe"
         return 0
      fi
   done
   die "$ecxbnm is not in PATH or ${calibre_locns[@]}"
   )
ecbin="$(find_ec_binary)"

convert_to_pdf() (
   # https://manual.calibre-ebook.com/generated/en/ebook-convert.html#pdf-output-options
   margin_pts=3
   set -x  # show actual cmdline
   "$1" "$2" "$3" --output-profile=ipad --use-profile-size \
 --pdf-page-margin-bottom=$margin_pts \
 --pdf-page-margin-left=$margin_pts \
 --pdf-page-margin-right=$margin_pts \
 --pdf-page-margin-top=$margin_pts
   )

for fnm in "$@"; do
   echo "arg=$fnm'"
   [[ -f "$fnm" ]] || die "$fnm does not name a file"
   sanspath="${fnm##*/}"         ; echo "sanspath=$sanspath'"    # https://stackoverflow.com/a/965069
   sansext="${sanspath%.*}"      ; echo "sansext=$sansext'"

   srcfnm="$fnm"                 ; echo "srcfnm=$srcfnm'"
   tgtfnm="$sansext.medtype.pdf" ; echo "tgtfnm=$tgtfnm'"
   if [[ -f "$tgtfnm" ]]; then
      echo "file $sansext already exists"
   else
      convert_to_pdf "$ecbin" "$srcfnm" "$tgtfnm"
   fi
done
