#!/usr/bin/env bash

# shellcheck disable=SC2120
die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

# stupid little script to

fetchremote="$(git remote -v | grep -F 'github.com' | head -n1 | cut -f2)"      ; echo "fetchremote=$fetchremote"
if [[ -z "$fetchremote" ]]; then
   echo "no entries matching 'github.com' in git remote -v output:"
   git remote -v | sed 's/^/   /'
   die
fi
fetchremote="${fetchremote/ (fetch)/}"
fetchremote="${fetchremote/ (push)/}"                             ; echo "fetchremote=$fetchremote"
fetchremote="${fetchremote/git@github.com:/https://github.com/}"  ; echo "fetchremote=$fetchremote"
# origin  git@github.com:fwmechanic/shell.git (push)
# start 'https://github.com/fwmechanic/shell.git'
start "$fetchremote"
