#!/bin/bash

# source: https://forum.level1techs.com/t/easy-to-follow-samba-autofs-mount/178658

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }
see() ( { set -x; } 2>/dev/null ; "$@" ) ;
inpath() { command -v "$1" >/dev/null ; }
dieifnotinpath() { inpath "$1" || die "$1 not in PATH"; }
chkpkg() { dpkg -l "$1" >/dev/null || die "pkg $1 not installed" ; }

inpath systemctl || die "this script written for systemctl-/systemd-based OS"
chkpkg autofs
chkpkg cifs-utils
dieifnotinpath smbclient

get_ssid() {
  if inpath nmcli; then  # preferred/modern approach
    # Avoid triggering a Wi-Fi rescan; we only need the active SSID
    nmcli -t --escape no -f ACTIVE,SSID dev wifi list --rescan no 2>/dev/null | awk -F: '$1=="yes"{print substr($0,5); exit}'
  elif inpath iwgetid; then  # legacy/deprecated approach
    iwgetid --raw
  else
    return 1
  fi
}

if [ "$1" ] ; then
   smb_server="$1"
else
   echo "optional samba domain name or server IP parameter omitted, trying SSID-based lookup"
   echo -n "SSID="
   ssid="$(get_ssid)" || die ", SSID-based lookup failed (no nmcli/iwgetid), giving up"
   echo -n "$ssid"
   lupfn="$HOME/.smbserver.for.ssid.$ssid"
   echo -n ", lupfn=$lupfn"
   read -r smb_server <"$lupfn" || die ", could not read server from $lupfn"
   echo ", '$smb_server'"
fi

# sample content for smbclient credential file:
#-------------------------
# username=smbusername
# password=smbpassword
smbclient_creds_fn="/home/$USER/.smb.credentials.$smb_server" ; test -f "$smbclient_creds_fn" || die "you haven't created $smbclient_creds_fn"
uid="$(id -u)"
gid="$(id -g)"
srcfn="$(mktemp /tmp/autofstmpconf.XXXXX)" ; chmod 644 "$srcfn"

for shnm in $(smbclient -A "$smbclient_creds_fn" -gL "$smb_server" | grep -F Disk | cut -d '|' -f2) ; do
    md="/mnt/remote/$shnm"
    echo "$md" -fstype=cifs,uid="$uid",gid="$gid",credentials="$smbclient_creds_fn",rw ://"$smb_server"/"$shnm" >> "$srcfn"
    test -d "$md" || sudo mkdir -p "$md"
done
num_smb_disks="$(<"$srcfn" wc -l)"
echo "$num_smb_disks SMB disk shares found on $smb_server"
# since `systemctl restart autofs` can be disruptive and time-consuming, avoid unless config has changed
destfn="/etc/auto.smbmedia"
if sudo /bin/sh -c "cmp -s '$destfn' '$srcfn'" ; then
   rm -f "$srcfn"
   echo "$destfn would not change, doing nothing"
else
   sudo /bin/sh -c "rm -f '$destfn' ; mv '$srcfn' '$destfn' && chown root:root '$destfn' && echo 'restarting autofs service' && systemctl restart autofs"
fi
