#!/usr/bin/env bash

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

command -v shellcheck > /dev/null || die "shellcheck not available"

[[ -n "$1" ]] || die "missing shell-script-filename"

out=".schk"
# set -x
# SC1017 file contains DOS newlines  KG: on Git for Windows bash this is not a problem, so ignore
shellcheck -f gcc -e SC1017 "$@" > "$out"
if [[ "$(wc -l "$out" | cut -d ' ' -f 1)" -gt 0 ]]; then
   edittempsync "$out"
else
   echo "clean: $*"
fi
rm -f "$out"
