#!/usr/bin/env bash

# keep in sync with %~dp0../winscripts/tagr.bat !!!
# eXclude .gitignored files per https://github.com/universal-ctags/ctags/issues/218#issuecomment-377717588

TAGS_FIELDS=+K+z+S+l+n
#            K           Kind of tag as full name
#              z         Include the "kind:" key in kind field (use k or K) in tags output
#                S       Signature of routine (e.g. prototype or parameter list)
#                  l     Language of input file containing tag
#                    n   Line number of tag definition
TAGS_EXTRAS=+f
#            f           Include [a tag record] for the base file name of every input file

TAGS_FNM_BASE=.k_edit_tags

rg --files | ctags -o "$TAGS_FNM_BASE" --totals=yes --tag-relative=yes --excmd=number --fields="$TAGS_FIELDS" --extras="$TAGS_EXTRAS" "$@" --recurse --links=no -L -
