#!/usr/bin/env bash

# divide a video omitting a middle section into out0.mp4
#                                          and  out1.mp4
# 20191121 wrote
#
# usage: viddiv fname mm:ss mm:ss

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

ifnm="$1" ; shift ;  [[    "$ifnm" ]] || die "parameters: fnm t0 t1"
t0="$1"   ; shift ;  [[    "$t0"   ]] || die "parameters: fnm t0 t1"
t1="$1"   ; shift ;  [[    "$t1"   ]] || die "parameters: fnm t0 t1"
                     [[ -f "$ifnm" ]] || die "$ifnm is not a file"
dfltofnm="out.mp4"
{ set -x 2> /dev/null ; }
vidsfxrmv "$ifnm" "$t0" || die ; mv "$dfltofnm" out0.mp4
vidpfxrmv "$ifnm" "$t1" || die ; mv "$dfltofnm" out1.mp4
