#!/usr/bin/env bash

# join videos out0.mp4 and out1.mp4 into out0.mp4
#
# 20191121 wrote
#
# usage: vidjoin

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

listfnm="vidjoin.tmp"

if1="${1:-"out0.mp4"}" ; [[ -f "$if1" ]] || die "$if1 is not a file"
if2="${2:-"out1.mp4"}" ; [[ -f "$if2" ]] || die "$if2 is not a file"

# ffmpeg behavior is dependent on even _output_ file's extension!
sanspath="${if1##*/}" #  ; echo "sanspath=$sanspath'"    # https://stackoverflow.com/a/965069
ext="${sanspath##*.}" ; [[ "$ext" ]] || die "no extension?"  #  ; echo "ext=$ext'"

dfltofnm="out.$ext"
# ffmpeg -i "concat:$if1|$if2" -c copy "$dfltofnm"

rm -f "$listfnm" || die "rm failed?"
cat <<HEREDOC > "$listfnm"
file '$if1'
file '$if2'
HEREDOC
cat "$listfnm"

# stdin process substitution
#    cat <( printf '%s\n%s\n' "file '$if1'" "file '$if2'" )
# would be better (no temp file to manage), BUT ffmpeg cannot accept it
# $ vidjoin
# /proc/4993/fd/63: No such file or directory

{ set -x 2> /dev/null ; }
# ffmpeg -hide_banner -y -f concat -safe 0 -i <( printf '%s\n%s\n' "file '$if1'" "file '$if2'" ) -c copy "$dfltofnm"
  ffmpeg -hide_banner -y -f concat -safe 0 -i "$listfnm" -c copy "$dfltofnm"
