#!/usr/bin/env bash

# join videos out0.mp4 and out1.mp4 into out0.mp4
#
# 20191121 wrote
#
# usage: vidjoin

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

dfltofnm="out.mp4"
listfnm="ffmpg_join.tmp"
# ffmpeg -i "concat:out0.mp4|out1.mp4" -c copy "$dfltofnm"

if1="${1:-"out0.mp4"}"
if2="${2:-"out1.mp4"}"

rm -f "$listfnm" || die "rm failed?"
cat <<HEREDOC > "$listfnm"
file '$if1'
file '$if2'
HEREDOC

# stdin process substitution
#    cat <( printf '%s\n%s\n' "file '$if1'" "file '$if2'" )
# would be better (no temp file to manage), BUT ffmpeg cannot accept it
# $ vidjoin
# /proc/4993/fd/63: No such file or directory

{ set -x 2> /dev/null ; }
# ffmpeg -hide_banner -y -f concat -safe 0 -i <( printf '%s\n%s\n' "file '$if1'" "file '$if2'" ) -c copy "$dfltofnm"
  ffmpeg -hide_banner -y -f concat -safe 0 -i "$listfnm" -c copy "$dfltofnm"
