#!/usr/bin/env bash

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }
see() ( { set -x; } 2>/dev/null ; "$@" ) ;
dieifnotinpath() { command -v "$1" >/dev/null || die "$1 not in PATH"; }

dieifnotinpath 7z

mkdir_or_die() {  # if already exists, do nothing (existing contents not disturbed)
   [[ -d "$1" ]] || mkdir "$1" || die "could not mkdir $1"
   [[ -d "$1" ]] ||               die "mkdir $1 failed"
   }
zf_saved="./_consumed" ; mkdir_or_die "$zf_saved"     # when making a bulk run, it's handy to be able to verify outcome by comparing the # of
zfdout="./_output"  ; mkdir_or_die "$zfdout"    # in vs out files (empty before starting! TODO: add a common date-code prefix to $zf_saved & $zfdout)

do1file() (
   fnm="$1"  # ; echo "fnm=$1'"
   [[ -f "$fnm" ]] || die "$fnm is not a file"

   # break down $fnm:
   fpath=""
   if [[ $fnm == */* ]]; then
      fpath="${fnm%/*}/"
      cd "$fpath" || die "cd to $fpath failed"
   fi                                   # ; echo "fpath=$fpath'"

   sanspath="${1##*/}"         ; echo "sanspath=$sanspath'"    # https://stackoverflow.com/a/965069
   ext="${sanspath##*.}"       ; echo "ext=$ext'"
   sansext="${sanspath%.*}"    ; echo "sansext=$sansext'"

   zf1if="$1"         # zf-do1file input file
   z1dind="$sansext"  # z1d input: a directory
   z1d_of="$z1dind.zip" z1d_od="z1d_$z1dind"  # on success, z1d creates $z1d_of && renames $z1dind to $z1d_od
   [[ -d "$z1dind" ]] && die "zf-do1file: z1d input-dir already exists"

   case "$ext" in
      mp3|mp4|m4a|m4b)  # degenerate/simple case: create zipfile consisting of dir containing input file
         see mkdir "$z1dind" && mv "$sanspath" "$z1dind/abook.$ext"    && echo "zf-do1file: z1d setup ok" &&
         z1d "$z1dind/" && [[ -f "$z1d_of" ]] && [[ -d "$z1d_od" ]] && echo "zf-do1file: z1d successful" &&
         rm -rf "$z1d_od" && mv "$z1d_of" "$zfdout/"                && echo "zf-do1file: z1d cleanup ok"
         return ;;
   esac

   # purpose: turn an input archive file (zip, rar) into a FLAT zip having
   #      within it a single directory bearing the basename of the source file
   #      (using z1d).
   #
   # why: so a simple decompress of the zip file on the end-use device
   #      (typically: phone) does not lose the name information embodied in the
   #      zip file's name; decompression of such a zip file results in a single
   #      new directory in the destination directory bearing the same name as the
   #      zipfile.  Decompressing many such zipfiles into a single destination
   #      directory (EX: phone's "Music" directory or "Audiobook" directory)
   #      keeps that directory well structured and easily maintainable, w/o any
   #      commingling of files from different zipfiles.
   #
   #      I chose zip file format because the Android Total Commander app does
   #      not (or: did not at the time this decision was made) have native unrar
   #      support, and aside from rar, zip is the most popular archive file
   #      format in the world (computer/phone users are most likely to have
   #      familiarity with it).  Also, there seem to be licensing constraints
   #      surrounding the creation of rar files, whereas I can easily create zip
   #      files cross-platform using 7z (7zip) or other tools.
   #
   #      RAR's main claim to fame seems to be support for error-correction
   #      records, at the cost of additional filesize needed to contain the error
   #      correction data records.  I figure a better approach is to have good
   #      backups of zip files at rest on my server.  Corruption during download
   #      is, since http came into use for downloads, no longer a problem, thus
   #      RAR adds no value in this regard.
   #
   #      Also, the audiobook and music "zip packages" I create here and
   #      elsewhere are *not* compressed, merely stored (because the content
   #      files (mp3, m4b, etc) are already compressed, and because I desire a
   #      low-overhead decompress operation on the phone), so use of alternate
   #      archive formats supporting higher degrees of compression is completely
   #      beside the point.
   #
   7z e -o"$z1dind" "$zf1if" || die "zf-do1file: 7z extraction failed"  # unzip $zf1if into a dir of its own name (sans extension)
   mv "$zf1if" "$zf_saved/"  # save $zf1if; do it now (and undo on error) because if $zf1if is a zip file, $zf1if and $z1d_of will collide
   restore_zf1if() { mv "$zf_saved/$zf1if" "./$zf1if" ; }
   z1d_cleanup() { [[ -d "$z1d_od" ]] && rm -rf "$z1d_od" ; } # true iff dir existed and rm'd
   z1d "$z1dind"      || { restore_zf1if ; z1d_cleanup ; die "zf-do1file: z1d failed" ; }
   [[ -f "$z1d_of" ]] || { restore_zf1if ; z1d_cleanup ; die "zf-do1file: expected z1d output file not found: $z1d_of" ; }
   mv "$z1d_of" "$zfdout/"
   z1d_cleanup || die "zf-do1file: expected z1d-renamed dir not found: $z1d_od"
   echo "------------------------------- zf successful -------------------------------"
   )

for fnm in "$@"; do
   do1file "$fnm"
done
